services:

   # конфигурация для сервисов по умолчанию в *этом* файле
   _defaults:
      autowire: true      # Автоматически внедряет зависимости в ваши сервисы.
      autoconfigure: true # Автоматически регистрирует ваши сервисы как команды, подписчики событий и т.д.


   Maris\Symfony\Geo\:
      resource: '../../src/'
      exclude: '../../src/{DependencyInjection,Entity,Interfaces}'


   Maris\Symfony\Geo\Calculator\GeoCalculator: '@Maris\Symfony\Geo\Calculator\SphericalCalculator'
   #Maris\Symfony\Geo\Service\GeoCalculator: '%geo.calculator%'


   Maris\Symfony\Geo\Calculator\SphericalCalculator:
      arguments:
         $ellipsoid: '%geo.ellipsoid%'
         $allowed: '%geo.allowed%'

   Maris\Symfony\Geo\Calculator\EllipsoidalCalculator:
      arguments:
         $ellipsoid: '%geo.ellipsoid%'
         $allowed: '%geo.allowed%'


   Maris\Symfony\Geo\Encoder\PolylineEncoder:
      arguments:
         $precision: "%geo.precision%"
